config/routes.rb
Dba::Application.routes.draw do
  get "home/index"

  get "home/about"

  get "home/help"

  resources :menus do
    resources :submenus
  end
  resources :submenus
  resources :posts

  root :to => 'home#index'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :icon, :title, :url
  validates :title, presence: true
  validates :icon, presence: true
  has_many :submenus, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/submenu.rb
class Submenu < ActiveRecord::Base
  belongs_to :menu
  validates :title, presence: true
  validates :icon, presence: true
  validates :url, presence: true
  attr_accessible :icon, :title, :url, :menu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.all
  end

  def about
  end

  def help
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/submenus_controller.rb
class SubmenusController < ApplicationController
  def create
    @menu = Menu.find(params[:menu_id])
    @submenu = @menu.submenus.create(params[:submenu])
    redirect_to menu_path(@menu)
  end
  def edit
    @submenu = Submenu.find(params[:id])
  end
  def update
    @submenu = Submenu.find(params[:id])
    respond_to do |format|
      if @submenu.update_attributes(params[:submenu])
        format.html { redirect_to @submenu.menu, notice: 'Submenu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submenu.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @submenu = Submenu.find(params[:id])
    @parent_menu = @submenu.menu
    @submenu.destroy

    respond_to do |format|
      format.html { redirect_to @parent_menu }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/submenus_helper.rb
module SubmenusHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/help.html.erb
<h1>Home#help</h1>
<p>Find me in app/views/home/help.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dba</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="col-lg-2">
        <ul class="nav navbar-nav">
          <a class="navbar-brand" href="/">Adslyw</a>
        </ul>
      </div>
      <div class="col-lg-10">
      </div>
  </nav>
</head>
<body>
    <div class="col-lg-2">
      <ul id='menu'>
        <% Menu.all.each do |menu| %>
          <%= render menu %>
        <% end %>
      </ul>
    </div>
    <div class="col-lg-8">
      <%= yield %>
    </div>
    <script>
        $(function () {
            $('#menu').metisMenu();
        });
    </script>
</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :icon %><br />
    <%= f.text_field :icon,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br />
    <%= f.text_field :url,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= submit_tag "Submit", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<li class="nav-divider"></li>
<li class="">
  <a href="<%= menu.url %>">
    <%= icon(menu.icon) %>
    <span class="link-title">&nbsp;<%= menu.title %></span>
    <% if !menu.submenus.empty? %>
      <span class="fa arrow"></span>
    <% end %>
  </a>
  <ul>
    <%= render menu.submenus %>
  </ul>
</li>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<table class="table">
  <tr>
    <th>Title</th>
    <th>Icon</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.title %></td>
    <td><%= menu.icon %></td>
    <td><%= menu.url %></td>
    <td><%= link_to 'Show', menu,class: "btn btn-success btn-xs" %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu),class: "btn btn-warning btn-xs" %></td>
    <td><%= link_to 'Destroy', menu,class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<ul id='menu'>
    <li class="">
      <a href="<%= @menu.url %>">
        <%= icon(@menu.icon) %>
        <span class="link-title">&nbsp;<%= @menu.title %></span>
        <% if !@menu.submenus.empty? %>
          <span class="fa arrow"></span>
        <% end %>
      </a>
      <ul>
        <% @menu.submenus.each do |submenu| %>
          <li class="">
            <a href="<%= edit_submenu_path(submenu) %>">
              <%= icon(submenu.icon) %>
              <span>&nbsp;<%= submenu.title %></span>
            </a>
            <%= link_to '删除', submenu, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        <% end %>
      </ul>
    </li>
</ul>
<h2>Add a submenu:</h2>
<%= form_for([@menu, @menu.submenus.build]) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :icon %><br />
    <%= f.text_field :icon,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br />
    <%= f.text_field :url,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= submit_tag "Submit", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>
<%= link_to 'Back', menus_path %>

app/views/partials/_menulist.html.erb
<ul id='menu'>
  <% :menus.each do |menu|%>
    <li class="">
      <a href="<%= menu.url %>">
        <%= icon(menu.icon) %>
        <span class="link-title">&nbsp;<%= menu.title %></span>
        <% if !menu.submenus.empty? %>
          <span class="fa arrow"></span>
        </a>
      <ul>
        <% menu.submenus.each do |submenu| %>
          <%=  render submenu %>
        <% end %>
      </ul>
      </li>
        <% else%>
      </a>
    </li>
        <% end %>
    <li class="nav-divider"></li>
  <% end %>
</ul>
<script>
    $(function () {
        $('#menu').metisMenu();
    });
</script>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/submenus/_form.html.erb
<%= form_for(@submenu) do |f| %>
  <% if @submenu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submenu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @submenu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :icon %><br />
    <%= f.text_field :icon,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br />
    <%= f.text_field :url,class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= submit_tag "Submit", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/submenus/_submenu.erb
<li class="">
  <a href="<%= submenu.url %>">
    <%= icon(submenu.icon) %>
    <span class="link-title">&nbsp;<%= submenu.title %></span>
  </a>
</li>

app/views/submenus/edit.html.erb
<h1>Editing submenu</h1>
<%= render 'form' %>
<%= link_to 'Back', @submenu.menu %>